### ISSUE TITLE
SuiteName crashes on some files

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#102]
We get a list index out of range error when trying to read 2bcz.cif.  Also 3cma.  Both cif and pdb files fail.

**Comment by russell-taylor** [comment]
[files.zip](https://github.com/ReliaSolve/cctbx_project/files/6901510/files.zip)
Here are the CIF files for those two.

There are a large number of other files also failing.

**Comment by Joymaker** [comment]
These files are fixed, and I believe I have fixed the root cause of all the other crashes. I had a list of half a dozen, and they are all now working.

**Comment by Joymaker** [comment]
Do we know of any remaining crashes?

**Comment by russell-taylor** [comment]
Rerunning now.  I'll let you know if any more show up.

**Comment by russell-taylor** [comment]
I'm running an 8-way parallel test now, so it should be done by the morning.

**Comment by russell-taylor** [comment]
It fails on 2bh2
[2bh2.zip](https://github.com/ReliaSolve/cctbx_project/files/6911148/2bh2.zip)

**Comment by russell-taylor** [comment]
Also fails on 3jag
```
taylorr@reliasolve-3:~/src/suitename_regression/outputs$ phenix.suitename -report -pointIDfields 7 -altIDfield 6 < 3jag.dangle
Traceback (most recent call last):
  File "/home/taylorr/rlab/cctbx_reliasolve/build/../modules/cctbx_project/mmtbx/command_line/suitename.py", line 10, in <module>
    suitename.run(args=sys.argv[1:])
  File "/home/taylorr/rlab/cctbx_reliasolve/modules/cctbx_project/mmtbx/programs/suitename.py", line 49, in run
    main(optionsIn=options, outFile=logger2, errorFile=logger)
  File "/home/taylorr/rlab/cctbx_reliasolve/modules/cctbx_project/mmtbx/suitename/suitename.py", line 126, in main
    suites = read(inFile, errorFile)
  File "/home/taylorr/rlab/cctbx_reliasolve/modules/cctbx_project/mmtbx/suitename/suitename.py", line 145, in read
    residues = readResidues(inFile)
  File "/home/taylorr/rlab/cctbx_reliasolve/modules/cctbx_project/mmtbx/suitename/suiteninput.py", line 50, in readResidues
    baseCode = fields[options.pointidfields - 1]
IndexError: list index out of range
```

**Comment by russell-taylor** [comment]
Here's the complete list so far (maybe 70% through the files):
```
Error computing new kinemage suiteness for 2bh2 (16 failures out of 1611)
Error computing new kinemage suiteness for 3jag (8 failures out of 495)
Error computing new kinemage suiteness for 3jah (11 failures out of 503)
Error computing new kinemage suiteness for 4w2h (12 failures out of 1011)
Error computing new kinemage suiteness for 4wqu (12 failures out of 2440)
Error computing new kinemage suiteness for 5dox (15 failures out of 2046)
Error computing new kinemage suiteness for 5el5 (6 failures out of 610)
Error computing new kinemage suiteness for 5el6 (6 failures out of 606)
Error computing new kinemage suiteness for 5ibb (19 failures out of 1635)
Error computing new kinemage suiteness for 6n9e (21 failures out of 1431)
Error computing new kinemage suiteness for 6nd5 (15 failures out of 2472)
Error computing new kinemage suiteness for 6o3m (11 failures out of 794)
Error computing new kinemage suiteness for 6oj2 (4 failures out of 191)
Error computing new kinemage suiteness for 6ucq (4 failures out of 788)
Error computing new kinemage suiteness for 6xqe (3 failures out of 546)
Error computing new kinemage suiteness for 6z1p (3 failures out of 307)
Error computing new kinemage suiteness for 7md7 (3 failures out of 225)
```

**Comment by Joymaker** [comment]
OK, this is a new one!  Here is the top of the .dangle file computed by mp_geo:

 Atom pair "HETATM 7780 FE2  SF4 A 501 .*.    Fe  " "ATOM    611  NE2 GLN A  93 .*.     N  " not found in MCL
 :1: C:1932: : :  A:__?__:__?__:-170.191:84.080:-106.982:-78.163
 :1: C:1933: : :  G:-52.056:152.427:48.315:71.500:-146.501:-58.250
 :1: C:1934: : :  C:-80.622:-175.316:70.350:73.320:-136.993:-70.474

I suppose I need to put in a recognizer for that particular error message; the C code blows on by and does the Suitename computation anyway, so I suppose I will do likewise. But I really doubt that we want to pass the error message through the way the C code does…?

**Comment by Joymaker** [comment]
Would it be a reasonable response to fix mp_geo itself so that it writes that message to standard error instead of standard output? It seems completely nonstandard to have it writing such things into a data stream.

**Comment by russell-taylor** [comment]
Fascinating.  Lets call this another case of https://github.com/ReliaSolve/cctbx_project/issues/109 where SuiteName should report an error and exit normally rather than crashing when it is fed a mal-formatted file.

I'll modify the test script to strip this line out of any dangle files and make an issue to fix mp_geo.

**Comment by russell-taylor** [comment]
That print is coming from down inside a library function.  I've reported it to Nigel.
