### ISSUE TITLE
SuiteName -report format failing on many files

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#115]
For the first and second ones, the issue is roundoff on the summary line.  The filter script should be modified to take this into account https://github.com/ReliaSolve/suitename_regression/blob/main/filter_report_diff_low_order_bit.py

```
taylorr@reliasolve-3:~/src/suitename_regression/outputs$ diff 1t0d.report.orig 1t0d.report.new 
93c93
<  non-1a  has 2 suites: average suiteness== 0.296 (power==3.00)
---
>  non-1a  has 2 suites: average suiteness== 0.295 (power==3.00)
```

```
Old vs. new comparison failed for 1k4b (11 out of 3273)
Old vs. new comparison failed for 1t0d (2 out of 285)
Old vs. new comparison failed for 1vy7 (18 out of 5125)
Old vs. new comparison failed for 1wwg (1 out of 320)
Old vs. new comparison failed for 2vqe (9 out of 2147)
Old vs. new comparison failed for 3cma (1 out of 44)
Old vs. new comparison failed for 3cme (1 out of 45)
Old vs. new comparison failed for 3ftm (5 out of 1957)
Old vs. new comparison failed for 3qjp (8 out of 2442)
Old vs. new comparison failed for 4aq7 (27 out of 5351)
Old vs. new comparison failed for 4lnt (19 out of 5052)
Old vs. new comparison failed for 4u1v (17 out of 4428)
Old vs. new comparison failed for 4v4q (20 out of 4206)
Old vs. new comparison failed for 4v5j (25 out of 4248)
Old vs. new comparison failed for 4v5m (17 out of 4251)
Old vs. new comparison failed for 4v7k (27 out of 5514)
Old vs. new comparison failed for 4v8p (20 out of 4162)
Old vs. new comparison failed for 4y4o (16 out of 3982)
Old vs. new comparison failed for 5eev (22 out of 4414)
Old vs. new comparison failed for 5fcj (10 out of 2932)
Old vs. new comparison failed for 5hau (10 out of 1640)
Old vs. new comparison failed for 5juu (10 out of 2631)
Old vs. new comparison failed for 5kpy (4 out of 407)
Old vs. new comparison failed for 5vaj (12 out of 3226)
Old vs. new comparison failed for 5ylz (6 out of 1232)
Old vs. new comparison failed for 6e8s (20 out of 3839)
Old vs. new comparison failed for 6gz3 (11 out of 3122)
Old vs. new comparison failed for 6hrm (26 out of 5476)
Old vs. new comparison failed for 6orl (9 out of 2565)
Old vs. new comparison failed for 6ucq (4 out of 819)
Old vs. new comparison failed for 7n2u (13 out of 3540)
Old vs. new comparison failed for 7nwi (10 out of 3510)

```

**Comment by Joymaker** [comment]
Can't even convert 2vqe:

mmtbx.mp_geo rna_backbone=True 2vqe.pdb  1>2vqe.dangle
Traceback (most recent call last):
  File "C:\Users\Ken\Desktop\Richardson\molprobity\build\..\modules\cctbx_project\mmtbx\command_line\mp_geo.py", line 7, in <module>
    mp_geo.run(sys.argv[1:])
  File "C:\Users\Ken\Desktop\Richardson\molprobity\modules\cctbx_project\mmtbx\validation\molprobity\mp_geo.py", line 120, in run
    grm = processed_pdb_file.geometry_restraints_manager()
  File "C:\Users\Ken\Desktop\Richardson\molprobity\modules\cctbx_project\mmtbx\monomer_library\pdb_interpretation.py", line 5713, in geometry_restraints_manager
    log=self.log,
  File "C:\Users\Ken\Desktop\Richardson\molprobity\modules\cctbx_project\mmtbx\conformation_dependent_library\mcl.py", line 117, in update
    raise e
  File "C:\Users\Ken\Desktop\Richardson\molprobity\modules\cctbx_project\mmtbx\conformation_dependent_library\mcl.py", line 113, in update
    sites_cart=pdb_hierarchy.atoms().extract_xyz(),
  File "C:\Users\Ken\Desktop\Richardson\molprobity\modules\cctbx_project\cctbx\geometry_restraints\manager.py", line 1077, in add_new_bond_restraints_in_place
    all_bonds_asu_table.add_pair_sym_table(self.shell_sym_tables[0])
RuntimeError: cctbx Internal Error: c:\users\ken\desktop\richardson\molprobity\modules\cctbx_project\cctbx/crystal/pair_tables.h(663): CCTBX_ASSERT(j_sym >= 0) failure.

**Comment by russell-taylor** [comment]
Right, that was the error where if it has an empty input file it should provide a 0-field.

The current issue still holds for 1t0d for which the output is listed above.  Please use that to fix the issue.

**Comment by russell-taylor** [comment]
Looking through them by hand, since this seems to be the last of the bugs.
