### ISSUE TITLE
6t5h_fragment score worse in Reduce2 than in Reduce

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#223]
Both scored against Probe2.

**Comment by russell-taylor** [comment]
There are slight differences in non-rotatable hydrogen directions between the models, presumably the same as in https://github.com/ReliaSolve/cctbx_project/issues/221.  Once that has been resolved, we can rerun.

**@todo:** There are two hydrogens added to A SEP 240 O1P in Probe2 that are not present in Probe. These do not affect the score, but are quite different between the two. Asked Jane and Dave about this.

**Comment by russell-taylor** [comment]
These should not be added.  Jane will work with Dorothee on this.  It may be that they should be added, Jane took another look at it.

**Comment by dcliebschner** [comment]
The two H atoms actually belong to OP2 and OP3. Odd placement was due to incorrect angle restraints for HOP2 and HOP3. Has been fixed and the two H atoms are now correctly placed (similar to https://www.rcsb.org/ligand/sep).

**Comment by russell-taylor** [comment]
Thanks!
