### ISSUE TITLE
Non-placed hydrogens

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#241]
I attach a fragment file that[https://app.zenhub.com/files/298640964/37114535-7cd2-4bbd-9e22-71fbc9816087/download](https://app.zenhub.com/files/298640964/37114535-7cd2-4bbd-9e22-71fbc9816087/download) I ran with reduce and reduce2. The reduce2 command is: mmtbx.reduce2 D:\data\Richardsons\6vw1_fragment.pdb add_flip_movers=True output.overwrite=True output.description_file_name=6vw1_fragment_description.txt output.file_name=6vw1_fragmentnewFH.pdb alt_id=a

    I also attach the resulting FH (flip + hydrogenate) files with Reduce2 being the new one.

    Many rotatable Hydrogens did not get placed by Reduce2 on NAG ("not enough restraints information"): HO3/4/6 on NAG 1/2 and BMA 3 and HO2 on BMA 3. They did get placed by Reduce.

    Also,  HD22 did not get added in Reduce2 but it was in Reduce. The relevant output was: "Atom HD22 ASN A 90 was not placed because it is involved in link_NAG-ASN".

**Comment by russell-taylor** [comment]
[6vw1_fragmentnewFH.zip](https://github.com/ReliaSolve/cctbx_project/files/11604565/6vw1_fragmentnewFH.zip)

**Comment by dcliebschner** [comment]
HO1/3/4/6 on NAG don't have ideal dihedral angles. I asked Nigel if they can be added.

**Comment by russell-taylor** [comment]
It looks like the NAG atoms are now being added.

HO2/3/4/6 are not being added to BMA C 3.

**Comment by russell-taylor** [comment]
Fixed as of 4/1/2024
