### ISSUE TITLE
Reduce2 run in 5NLQ produces conflicting angle restraints

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#278]
When running the command: `mmtbx.reduce2 add_flip_movers=True output.overwrite=True 5nlq.pdb`

```
                      ----------Adding Hydrogens----------

Sorry: Conflicting angle restraints:
  1. definition from: residue: HIC%NH3, conformer "A"
  2. definition from: residue: HIC%NH3, conformer "A"
  atoms:
    "HETATM   13  H2  HIC A   1 .*.     H  "
    "HETATM    1  N   HIC A   1 .*.     N  "
    "HETATM    2  CA  HIC A   1 .*.     C  "
```

**Comment by russell-taylor** [comment]
Nigel reports that this turned up a fundamental issue that should be solved in a day or two.

**Comment by nwmoriarty** [comment]
This should be corrected for all amino acids (this was an issue because the non-standard AA was at the N terminal) in the GeoStd.

**Comment by russell-taylor** [comment]
Works as of commit d57fe7eed2540734b8b2e84049d6848776bcd71f of geostd.
