### ISSUE TITLE
Undowser2

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#286]
Make an undowser2 that uses probe2
	https://github.com/cctbx/cctbx_project/blob/master/mmtbx/programs/undowser.py
	https://github.com/cctbx/cctbx_project/blob/master/mmtbx/validation/undowser.py
	https://github.com/cctbx/cctbx_project/blob/master/mmtbx/validation/regression/tst_undowser.py

**Comment by russell-taylor** [comment]
@chrissciwilliams what are good PDB files to run on to test whether we're getting the same water collisions in undowser2 as undowser?

**Comment by russell-taylor** [comment]
(done) Test on both single-model and multi-model files. Probably 1LPL, according to tst_undowser.py

The tst_undowser.py fails, and the program returns no clashes for 1LPL. Asked Christopher and Jane about this. Running in 1LPL.cif under Linux does show collisions, but tst_undowser.py still fails (maybe it can't find probe?).

The phenix.undowser_validation program also returns nothing for 1ssx on Windows, but it returns a number of clashes on Linux (last update Jan 29), also when rebuilt in the undowser2 branch. This is a file that Christopher thought should exhibit all of the types of clashes.

Running on 1LPL produces 6 waters of 86 with clashes in undowser and 7 on undowser2.

**Comment by russell-taylor** [comment]
(done) Make a regression test for it once it is working and add it to the list of those that are run.

**Comment by chrissciwilliams** [comment]
1ssx is a rich source of water clashes - it populates all of UnDowser's
current categories.  It's probably the most useful single file I have on
hand.

Some other useful files:
1gwe has many clashes with alternate-conformation waters
1eb6 has lots of water-water clashes
1LpL should work, and is a simpler file with no
alternates-conformation/water interactions.

-Christopher Williams
---Richardson Lab, Duke University

**Comment by russell-taylor** [comment]
(done) When we try to run on 1SSX, it has a Sorry with a Hydrogen with 3 bonds on it. Modified Probe2 to allow multiple bonds for a hydrogen, which can happen when we have screwed up alternate conformations.

**Comment by russell-taylor** [comment]
Added in the undowser2 branch, which has been pull requested into master.
