### ISSUE TITLE
Make CCTBX/SuiteName output compatible with existing code

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#64]
Removing space between == and number.
Adding back in power report.
Anything else that the diff turns up in the regression testing.

**Comment by russell-taylor** [comment]
Also make the command-line arguments compatible (able to read from standard input):

taylorr@reliasolve-3:~/src/suitename_regression$ phenix.suitename -report -pointIDfields 7 -altIDfield 6 < tmp2.out
Sorry: Some PHIL parameters are not recognized by suitename.
 Please run this program with the --show-defaults option to see what parameters
are available.
 PHIL parameters in files should be fully specified (e.g. "output.overwrite"
instead of just "overwrite")

**Comment by russell-taylor** [comment]
[tmp2.zip](https://github.com/ReliaSolve/cctbx_project/files/6687100/tmp2.zip)
This was the input file.

**Comment by russell-taylor** [comment]
Here are several input .dangle files and the output of the original SuiteName program.  The new version cannot run with its input coming from standard input, so these output files are all blank.  @Joymaker this should give you some files to try on.

The three command-line arguments are:
- -report -pointIDfields 7 -altIDfield 6
- -string -oneline -pointIDfields 7 -altIDfield 6
- -kinemage -pointIDfields 7 -altIDfield 6

[outputs.zip](https://github.com/ReliaSolve/cctbx_project/files/6718159/outputs.zip)

**Comment by russell-taylor** [comment]
The code reports that it does not recognize the -oneline command-line argument, which MolProbity gives along with -string for one of the ways it can be run.

**Comment by russell-taylor** [comment]
When run with -kinemage, it says "read no residues: perhaps wrong algernate code".

**Comment by Joymaker** [comment]
Turns out the suggestion in my error message was actually right in this case. The main problem is that you were asking for -altIDfield 6 in a format that was actually using field 5 (zero based) as the alt ID, and field 6 as the residue ID. Actually, unless you are specifying altID there is no reason to specify altIDfield, It won't be used.

Having dealt with that issue, 1f1t and 4f1n and tmp2 match the past perfectly, 5imq gets genuine computational differences, which I will look at further.

**Comment by russell-taylor** [comment]
So... the original version of SuiteName works with those command line arguments and the new one does not.  Perhaps the zero base is an incorrect assumption?

**Comment by russell-taylor** [comment]
Also still waiting on a fix for -oneline and then I think the command line parsing will be working for fully-spelled-out arguments in the cases that we're using.

**Comment by russell-taylor** [comment]
The command-line arguments come from the MolProbity runs; not sure why they specified the altIDfield without specifying altID.

**Comment by Joymaker** [comment]
-oneline became default behavior.  I think that was the outcome of a meeting long ago, but perhaps we should review that.  I will restore it as an accepted flag.

**Comment by Joymaker** [comment]
Bugs fixed:

-oneline works again.
-altidfield now uses one-based counting. So did the old C version, although this fact was deeply hidden in the code, and nowhere documented.

**Comment by russell-taylor** [comment]
This is getting much closer!
- The -oneline -string now seems to be the same except for a difference of having a missing newline in the new version compared to the old.
- The -report seems to be the same except that the new is missing an outlier type report at the end of the line.
- The -kinemage seems to match except for a filled-in letter code in the last '' before the comma, using 3 digits past the decimal rather than 2, and having an extra space between numbers.

**Comment by russell-taylor** [comment]
[diffs.zip](https://github.com/ReliaSolve/cctbx_project/files/6733360/diffs.zip)
Here are the files.  'diff' can be used on Linux or a mac or Cygwin/minGW on Windows to compare them.

**Comment by russell-taylor** [comment]
@Joymaker  With -oneline -string, the last character in the original C code file is 0x0a but in the python version it is 0x00.

**Comment by russell-taylor** [comment]
@Joymaker backslash does not work inside an f string.  I wonder if this is the problem?

**Comment by russell-taylor** [comment]
No, that appears to be working -- maybe writeFinalOutput should be modified to add a final end of line \n.

**Comment by russell-taylor** [comment]
Yeah, that did it.

**Comment by russell-taylor** [comment]
[report_diffs.zip](https://github.com/ReliaSolve/cctbx_project/files/6743954/report_diffs.zip)
@Joymaker I found differences in the reports (but not the -oneline) for a couple of other files.  Here they are, along with their dangle input files.

**Comment by russell-taylor** [comment]
@Joymaker Here are some rounding and wannabe differences in 5imr for you to take a look at once the kinemage formatting is done.

[5imr.zip](https://github.com/ReliaSolve/cctbx_project/files/6750957/5imr.zip)

**Comment by russell-taylor** [comment]
@Joymaker Do you have an ETA for the new kinemage output and/or other bug fixes to be ready to test?

**Comment by Joymaker** [comment]
Down to three discrepancies in my list:  3cgp, 4z4d, 5b2q

**Comment by russell-taylor** [comment]
@Joymaker With the new code from today, there are differences in the output for the -string because the extra spaces are making their names into the output file.  The kinemage formats also differ and are both still using 2 digits past the decimal point.

**Comment by Joymaker** [comment]
3 digits vs 2 digits is fixed

**Comment by Joymaker** [comment]
Are we trying to be radically backward compatible while reading CIF?  I wasn't aware that was a goal.

**Comment by russell-taylor** [comment]
What branch of the C code is using 3 digits?

**Comment by russell-taylor** [comment]
My script compares running on the PDB file to running on the CIF file for the same molecule to determine whether things are working.  It is finding differences.  I could try to make it determine which differences are irrelevant and ignore them but I expect it to be just as easy to fix them so they don't happen in the first place.  We do need to check for different behaviors when loading the two file types, as we have already seen some of these happening.

**Comment by Joymaker** [comment]
Master branch

**Comment by russell-taylor** [comment]
@Joymaker We're getting a lot closer!  We now get through the first several files with no significant differences in any of the formats.

We are seeing a difference of missing "'O ' white , " in 5imr Kinemage files.  We're also seeing what look like round-off errors in the report output and also different numbers of suites.
[5imr_results.zip](https://github.com/ReliaSolve/cctbx_project/files/6816188/5imr_results.zip)

**Comment by russell-taylor** [comment]
@Joymaker There is also a difference between the strings in 2ake, with A1aU1 being replaced by A1aU! about 3/4 of the way through:

```
taylorr@reliasolve-3:~/src/suitename_regression/outputs$ diff 2ake.string.orig 2ake.string.new
1c1
< __G1aA1aC!!C1aU1aC1aG!!U1cG!!G1cC1aG1cC1cA!!A!!U!!G!!G1gU3dA7aG!!C!!G1aC1aG!!U!!C!!U1aG1aA1aC!!U!!C!!C1aA1aG1aA1aU1aC1aA1cG1aA1aA1aG!!G!!U!!U!!G1cC1aG1cU!!G1aU1aU!!C1aG1mA!!A1aU1LC1aA1aC1aG1aU1aC1aG1aG1aG1aG1cU!!C!!A
---
> __G1aA1aC!!C1aU1aC1aG!!U1cG!!G1cC1aG1cC1cA!!A!!U!!G!!G1gU3dA7aG!!C!!G1aC1aG!!U!!C!!U1aG1aA1aC!!U!!C!!C1aA1aG1aA1aU1aC1aA1cG1aA1aA1aG!!G!!U!!U!!G1cC1aG1cU!!G1aU1aU!!C1aG1mA!!A1aU!!C1aA1aC1aG1aU1aC1aG1aG1aG1aG1cU!!C!!A

```

**Comment by russell-taylor** [comment]
@Joymaker We get a list index out of range error when trying to read 2bcz.cif.

**Comment by russell-taylor** [comment]
@Joymaker The new behavior where the code returns nonzero when it finds no RNA breaks my test for the code failing on some PDB and CIF files (for example, 4jf2.cif fails but 1gci.cif has no RNA).  Please make the return code 0 when the model has no RNA.  It is okay to print to standard error that the model has no RNA.

**Comment by russell-taylor** [comment]
**@todo:** Waiting on https://github.com/ReliaSolve/Molprobity2/issues/155
**@todo:** Waiting on https://github.com/ReliaSolve/Molprobity2/issues/156
**@todo:** Waiting on https://github.com/ReliaSolve/cctbx_project/issues/102

**Comment by Joymaker** [comment]
Time for a new run. With the latest commits to both Ccode and Python code, I know of no causes for error. Apart from the confusion with 4Q1N, which I have commented separately.

**Comment by russell-taylor** [comment]
[out.txt](https://github.com/ReliaSolve/cctbx_project/files/6907416/out.txt)
Here are the results from the first 17,000 files.  Ignore the complaints about "XXX PDB value =", but the others are all still potential problems: "Error computing ..." and "Old vs. new ..."

I'll take a look at a sample of them and either update existing issues or make new ones.

**Comment by russell-taylor** [comment]
It is getting a lot closer!

**Comment by russell-taylor** [comment]
Fixed the filters to not crash and to handle more cases.  Fixed the parallel script to not race on the temporary files.

Rerunning the parallel version.

**Comment by russell-taylor** [comment]
Closing this group issue, the remaining issues are covered by other issues.
