### ISSUE TITLE
The SuiteName internal format when reading PDB files should match that of mp_geo

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#66]
It is okay to add the 4-letter PDB file name into the proper place in the output line for the PDB-parsing case.

**Comment by russell-taylor** [comment]
This was regarding the question of whether we should match dangle format or mp_geo format.  It does not need to byte-for byte match unless something in the line will feed forward to the final output.  Also, it is fine for the new code to print out a different set of residues than mp_geo does.

**Comment by Joymaker** [comment]
Have run an extensive test of dangle-style input versus PDB input. Seeing discrepancies where the PDB version finds more suites, but no formatting discrepancies.
