### ISSUE TITLE
phenix.suitename gets different results when run on 1hhx.cif than 1hhx.pdb

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#83]
I modified the programs/suitename.py to call cif files PDB format so that they get fed to the model reader.  It can run on the file, but it gets a different answer from the cif file and from the pdb file that was made from it using the cctbx ciff-to-pdb converter.

**Comment by Joymaker** [comment]
Interesting. The difference is precisely that exclusion of DNA residues is being done on the PDB file but not on the CIF file. I will look into it deeper.

**Comment by Joymaker** [comment]
Ooh, that was devious! Suitename is programmed to expect three character residue codes in all cases, even if they contain some blanks. Reading a PDB file meets that standard. Reading a CIF file was delivering 2 character residue codes, 'DG', 'DC', etc.  I have changed it to work with those...but I don't know if CIF will give us more trouble where that came from!

**Comment by russell-taylor** [comment]
I don't see the commit in the suitename branch of reliasove/cctbx_project.  Once it is there, I'll restart the run.

**Comment by russell-taylor** [comment]
... or I could read carefully to the end of your message and see that it will be coming later.

**Comment by Joymaker** [comment]
Glad I didn't commit in haste! The wormhole was much deeper than I thought.

When reading residues from a hierarchy structure, Suitename now pads a residue name with spaces on the left as needed to make it three characters long, before further processing. This has given me no-difference results for several PDB/CIF pairs, I'm hopeful that this fixes it.
