### ISSUE TITLE
SuiteName fails to run on 4jf2 for either the CIF file or the PDB file

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#85]
This is when it is run just on the input file with the -report option.

**Comment by Joymaker** [comment]
It runs, and finds one suite more than the mp_geo based version.  Unlike other examples I have seen, this one had the mess at the very beginning, requiring a rethink to my "detour" strategy. Had to start the "detour" backbone from scratch rather than have a jumping off point to work from.
