### ISSUE TITLE
Error print statement left behind? causing suitename differences

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#97]
There is a raw object information print happening when reading CIF and PDB files that is presumably not needed for final outputs.  It is exposing a pointer, which is going to be different between runs.

```
taylorr@reliasolve-3:~/src/suitename_regression/outputs$ cat 1f1t.cif 
[<iotbx_pdb_hierarchy_ext.chain object at 0x7f0d69b80a28>]
chain  A
taylorr@reliasolve-3:~/src/suitename_regression/outputs$ cat 1f1t.pdb 
[<iotbx_pdb_hierarchy_ext.chain object at 0x7fd81212e5b0>]
chain  A
```

**Comment by russell-taylor** [comment]
This is on commit 18b6cf9801313dce8d15c1516c66d0e7371f1f28

**Comment by Joymaker** [comment]
Found and fixed.

**Comment by Joymaker** [comment]
testing exposed deeper problem with PDB handling.  Hold off on any re-test.

**Comment by Joymaker** [comment]
Fixed that too.
